### ISSUE TITLE
a client-side exception has occurred (see the browser console for more information). 

### ISSUE THREAD

**Issue by mayukhpankaj** [risixdzn/gymn#165]
![image](https://github.com/risixdzn/gymn/assets/40158577/dfbc72ec-51c8-428b-8fec-7385604ce78d)

Just after Gym Owner registration this occurred - Registrar
Preencha os campos abaixo para registrar-se no aplicativo

route - https://gymn.vercel.app/auth

**Comment by risixdzn** [comment]
Hey @mayukhpankaj ! Thanks for reporting this bug!

Sorry for the late response, but the issue that you encountered was related to the Google Translate extension, which replaces texts on the page for font tags, which are not recognized by React Dom and causes a crash.

See https://github.com/facebook/react/issues/11538#issuecomment-390386520 for more details.

Unfortunately, you can face this bug on other parts of Gymn because this is a React quirk, but feel free to open another issue if you encounter it again.
